project:
  type: website
  resources:
  - assets/
  - CNAME
  - publications.json
  output-dir: _site

website:
  title: "Nicholas P. Sweeney"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Articles"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    left: "Website designed by Nicholas P. Sweeney"
    right: '<a href="https://github.com/nicksweeney313/NPS-WEB" target="_blank" rel="noopener">Open access on the Author''s GitHub</a>'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
